version: '2'

services:
  app_cassandra:
    build: ./app_cassandra
    container_name: app_cassandra
    ports:
      - 9043:9042
    environment:
      - ADDITIONAL_JVM_OPTS=-DZipkinTracing.kafkaCollectorAddress=$NET_IP:9092 -DZipkinTracing.collectorMethod=kafka
